---
permalink: online-help/concept-constituent-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: La página del explorador de rendimiento/volumen de componente proporciona información detallada del rendimiento para el componente FlexGroup seleccionado. 
---
= Página del explorador de volumen de componentes/rendimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La página del explorador de rendimiento/volumen de componente proporciona información detallada del rendimiento para el componente FlexGroup seleccionado.

La página del Explorador de rendimiento/volumen de componente le permite realizar un seguimiento y comparar el rendimiento de los componentes durante un periodo de tiempo específico, lo que ayuda a la resolución de problemas y a optimizar el rendimiento de un volumen FlexGroup y sus volúmenes constituyentes.

Con la funcionalidad de Ver y comparar puede comparar el rendimiento de este volumen constituyente con:

* el agregado en el que reside este volumen constituyente
* El equipo virtual de almacenamiento en el que reside este volumen que forma parte del componente
* El volumen FlexGroup al que pertenece el componente
* otros volúmenes que se encuentran en el mismo agregado


La página del Explorador de volúmenes de componente/rendimiento le permite:

* Ver los problemas relacionados con los umbrales y sus detalles
* Realice un seguimiento y compare los datos de rendimiento de los componentes
* Investigar y solucionar problemas relacionados con los umbrales
* Investigue y solucione problemas de rendimiento


[NOTE]
====
Para los volúmenes de protección de datos (DP), solo se muestran los valores de contador del tráfico generado por el usuario.

====