---
permalink: online-help/reference-performance-all-lifs-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista rendimiento: Todas las interfaces de red muestra una descripción general de los eventos de rendimiento, los datos y la información de configuración de cada interfaz de red \(LIF\) que supervisa esta instancia de Unified Manager. Esta página le permite supervisar rápidamente el rendimiento de las interfaces y solucionar problemas de rendimiento y eventos de umbral.' 
---
= Performance: Vista de todas las interfaces de red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Performance: All Network interfaces muestra una descripción general de los eventos de rendimiento, los datos y la información de configuración de cada interfaz de red (LIF) que está supervisando mediante esta instancia de Unified Manager. Esta página le permite supervisar rápidamente el rendimiento de las interfaces y solucionar problemas de rendimiento y eventos de umbral.

De forma predeterminada, los objetos de las páginas de vista se ordenan en función de la gravedad del evento. Los objetos con eventos críticos se enumeran primero y los objetos con eventos de advertencia aparecen en segundo lugar. Esto proporciona una indicación visual inmediata de los problemas que deben abordarse.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta (de estado, rendimiento, capacidad, etc.), realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para limitar la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv`, `.pdf`, o. `.xlsx` archivo. Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

Puede asignar directivas de umbral de rendimiento a cualquier objeto de las páginas de inventario de objetos o borrar directivas de umbral mediante los botones *asignar directiva de umbral de rendimiento* y *Borrar directiva de umbral de rendimiento*.

[NOTE]
====
Las interfaces que se enumeran en esta página incluyen LIF de datos, LIF clúster, LIF de gestión de nodos y LIF de interconexión de clústeres. Unified Manager no utiliza ni muestra las LIF del sistema.

====
Consulte xref:reference-lif-performance-fields.adoc[Campos de rendimiento de la interfaz de red] para obtener descripciones de todos los campos de esta página.
