---
permalink: online-help/reference-assign-performance-threshold-policy-page-opm.html 
sidebar: sidebar 
keywords:  
summary: Es posible usar la página Assign Performance Threshold Policy para asignar una política de umbral de rendimiento a uno o más objetos de almacenamiento. 
---
= Asigne la página Performance Threshold Policy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar la página Assign Performance Threshold Policy para asignar una política de umbral de rendimiento a uno o más objetos de almacenamiento.

La lista de políticas se completa únicamente con las políticas válidas para el tipo de objeto de almacenamiento seleccionado.

Seleccione la directiva que desea aplicar al objeto u objetos y, a continuación, haga clic en *aplicar directiva*.

En algunos casos, es posible que se devuelva un mensaje de error cuando intente aplicar una política, por ejemplo, al aplicar una política de combinación a un volumen FlexGroup, donde el segundo contador incluye un objeto nodo o agregado. Como los volúmenes FlexGroup pueden estar distribuidos por varios nodos y agregados, esta operación no está permitida.
