---
permalink: online-help/reference-lag-thresholds-for-unmanaged-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: La página umbrales de relación le permite configurar valores globales de umbral de error y advertencia de desfase para relaciones de protección no administradas, de modo que se le notifique y pueda tomar medidas cuando se produzcan errores de umbral o de desfase. Los cambios realizados en esta configuración se aplican durante la siguiente actualización programada. 
---
= Umbrales de relación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La página umbrales de relación le permite configurar valores globales de umbral de error y advertencia de desfase para relaciones de protección no administradas, de modo que se le notifique y pueda tomar medidas cuando se produzcan errores de umbral o de desfase. Los cambios realizados en esta configuración se aplican durante la siguiente actualización programada.

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

Los eventos se generan cuando se cumple un umbral tanto para los volúmenes como para las máquinas virtuales de almacenamiento. Puede tomar acciones correctivas para tales eventos. Los eventos ahora se crean para las relaciones de los equipos virtuales de almacenamiento pero se bloquean para las relaciones de los componentes dentro de la configuración de recuperación ante desastres del equipo virtual de almacenamiento. Esto ayuda a evitar que se produzcan demasiados eventos para una relación. La configuración de umbral de desfase para relaciones no administradas está habilitada de forma predeterminada y también se proporciona a los equipos virtuales de almacenamiento.

El umbral de desfase especifica un porcentaje que no debe superar el tiempo de desfase. Con un ejemplo de una hora, si el umbral de desfase se define como 150%, recibirá un evento cuando el tiempo de retraso sea superior a 1.5 horas.



== Área umbrales de desfase para relaciones no administradas

El área de desfase le permite establecer umbrales de desfase en las relaciones no administradas para las siguientes condiciones:

* *Advertencia*
+
Especifica el porcentaje en el que la duración de la demora es igual o superior al umbral de aviso de desfase:

+
** Valor predeterminado: 150 %
** Eventos generados: Aviso de desfase en la relación de SnapMirror o aviso de desfase en la relación de SnapVault
** Gravedad del evento: Advertencia


* *Error*
+
Especifica el porcentaje en el que la duración de la demora es igual o superior al umbral de error de desfase:

+
** Valor predeterminado: 250 %
** Eventos generados: Error de desfase en la relación de SnapMirror o error de desfase en la relación de SnapVault
** Gravedad del evento: Error




Además, puede desactivar un evento de advertencia o error para que se active desde cualquier cantidad de umbral de desfase desactivando la casilla situada junto a Activado.
