---
permalink: online-help/reference-edit-cluster-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: El cuadro de diálogo Edit Cluster le permite modificar la configuración de conexión de un clúster existente, incluidas la dirección IP, el puerto y el protocolo. 
---
= Cuadro de diálogo Edit Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El cuadro de diálogo Edit Cluster le permite modificar la configuración de conexión de un clúster existente, incluidas la dirección IP, el puerto y el protocolo.

Puede editar los siguientes campos:

* *Nombre de host o Dirección IP*
+
Permite especificar el FQDN, el nombre corto o la dirección IP (IPv4 o IPv6) de la LIF de gestión de clústeres que se utiliza para conectarse con el clúster.

* *Nombre de usuario*
+
Permite especificar un nombre de usuario que se puede utilizar para iniciar sesión en el clúster.

* *Contraseña*
+
Permite especificar una contraseña para el nombre de usuario especificado.

* *Puerto*
+
Permite especificar el número de puerto utilizado para conectarse al clúster. El puerto predeterminado es 443 para HTTPS.


