---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Capacity: All Clusters permite ver información resumida sobre la capacidad de almacenamiento y la utilización en todos los clústeres. Esta información le ayuda a comprender los posibles riesgos de capacidad y a realizar las acciones adecuadas para reequilibrar las cargas de trabajo.' 
---
= Capacity: Vista All Clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Capacity: All Clusters permite ver información resumida sobre la capacidad de almacenamiento y la utilización en todos los clústeres. Esta información le ayuda a comprender los posibles riesgos de capacidad y a realizar las acciones adecuadas para reequilibrar las cargas de trabajo.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta (de estado, rendimiento, capacidad, etc.), realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para limitar la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv`, `.pdf`, o. `.xlsx` archivo. Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

Consulte xref:reference-cluster-capacity-fields.adoc[Campos de capacidad del clúster] para obtener descripciones de todos los campos de esta página.
