---
permalink: online-help/reference-capacity-all-qtrees-view.html 
sidebar: sidebar 
keywords:  
summary: 'La capacidad: Toda la vista Qtrees permite ver información sobre la capacidad y la utilización de los qtrees en todos los clústeres. Esta información le permite comprender los posibles riesgos de la capacidad, así como ver el porcentaje de disco configurado y utilizado y el número de archivos.' 
---
= Capacidad: Toda la vista Qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La capacidad: Toda la vista Qtrees permite ver información sobre la capacidad y la utilización de los qtrees en todos los clústeres. Esta información le permite comprender los posibles riesgos de la capacidad, así como ver el porcentaje de disco configurado y utilizado y el número de archivos.

De forma predeterminada, los objetos de las páginas de vista se ordenan en función de la gravedad del evento. Los objetos con eventos críticos se enumeran primero y los objetos con eventos de advertencia aparecen en segundo lugar. Esto proporciona una indicación visual inmediata de los problemas que deben abordarse.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta (de estado, rendimiento, capacidad, etc.), realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para limitar la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv`, `.pdf`, o. `.xlsx` archivo. Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

Puede personalizar la configuración del umbral de capacidad para uno o más qtrees mediante el botón *Editar umbral*.

Consulte xref:reference-qtree-capacity-fields.adoc[Campos de capacidad de Qtree] para obtener descripciones de todos los campos de esta página.
