---
permalink: online-help/reference-performance-qos-policy-groups-view.html 
sidebar: sidebar 
keywords:  
summary: La vista QoS Policy Groups muestra los grupos de políticas de calidad de servicio disponibles en los clústeres que supervisa Unified Manager. Esto incluye las políticas de calidad de servicio tradicionales, las políticas de calidad de servicio adaptativas y las políticas de calidad de servicio asignadas mediante los niveles de servicio de rendimiento. 
---
= Rendimiento: Vista QoS Policy Groups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista QoS Policy Groups muestra los grupos de políticas de calidad de servicio disponibles en los clústeres que supervisa Unified Manager. Esto incluye las políticas de calidad de servicio tradicionales, las políticas de calidad de servicio adaptativas y las políticas de calidad de servicio asignadas mediante los niveles de servicio de rendimiento.

Los controles de la parte superior de la página le permiten seleccionar una vista concreta en función del tipo de política de QoS que le interese, realizar búsquedas para localizar objetos específicos, crear y aplicar filtros para restringir la lista de datos mostrados, añadir/eliminar/reordenar columnas en la página, y exportar los datos de la página a un `.csv` o. `.pdf` archivo.

Después de personalizar la página, puede guardar los resultados como una vista personalizada y, a continuación, programar un informe de estos datos para que se genere y se envíe por correo electrónico regularmente.

Consulte xref:reference-qos-policy-group-fields.adoc[Campos del grupo de políticas de QoS] para obtener descripciones de todos los campos de esta página.
