---
permalink: online-help/task-viewing-details-about-cifs-shares.html 
sidebar: sidebar 
keywords: SMB,CIFS 
summary: 'Puede ver detalles sobre todos los recursos compartidos SMB/CIFS, como el nombre del recurso compartido, la ruta de unión, que contiene objetos, la configuración de seguridad y las políticas de exportación definidas para el recurso compartido. Use la vista Health: All SMB Shares para ver todos los recursos compartidos de SMB en todos los clústeres supervisados, y use la página de detalles Storage VM / Health para ver todos los recursos compartidos de SMB en una máquina virtual de almacenamiento específica \(SVM\).' 
---
= Ver detalles sobre los recursos compartidos de SMB/CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver detalles sobre todos los recursos compartidos SMB/CIFS, como el nombre del recurso compartido, la ruta de unión, que contiene objetos, la configuración de seguridad y las políticas de exportación definidas para el recurso compartido. Use la vista Health: Todos los recursos compartidos de SMB para ver todos los recursos compartidos de SMB en todos los clústeres supervisados y use la página de detalles Storage VM / Health para ver todos los recursos compartidos de SMB en una máquina virtual de almacenamiento (SVM) específica.



== Antes de empezar

* La licencia de CIFS debe estar habilitada en el clúster.
* Se deben configurar las interfaces de red que sirven a los recursos compartidos de SMB/CIFS.
* Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.




== Acerca de esta tarea

[NOTE]
====
No se muestran los recursos compartidos de las carpetas.

====


== Pasos

. En el panel de navegación de la izquierda, siga los siguientes pasos dependiendo de si desea ver todos los recursos compartidos de SMB/CIFS o solo los recursos compartidos de una SVM en particular.


[cols="2*"]
|===
| Para... | Siga estos pasos... 


 a| 
Ver todos los recursos compartidos de SMB/CIFS
 a| 
Haga clic en *almacenamiento* > *Recursos compartidos SMB*



 a| 
Vea los recursos compartidos de SMB/CIFS para un único SVM
 a| 
. Haga clic en *almacenamiento* > *Storage VMs*
. Haga clic en la SVM para la que desea ver los detalles de los recursos compartidos de SMB/CIFS.
. En la página de detalles Storage VM / Health, haga clic en la ficha *Recursos compartidos SMB*.


|===