---
permalink: online-help/task-viewing-the-cluster-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Health: All Clusters se puede usar para ver el inventario de clústeres. La vista Capacity: All Clusters permite ver información resumida sobre la capacidad de almacenamiento y la utilización en todos los clústeres.' 
---
= Ver la lista del clúster y sus detalles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Health: All Clusters se puede usar para ver el inventario de clústeres. La vista Capacity: All Clusters permite ver información resumida sobre la capacidad de almacenamiento y la utilización en todos los clústeres.



== Antes de empezar

Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.



== Acerca de esta tarea

También puede ver detalles de cada clúster, como el estado del clúster, la capacidad, la configuración, las LIF, los nodos, Y los discos en ese clúster mediante la página de detalles Cluster / Health.

Los detalles en la vista Health: All Clusters, Capacity: All Clusters y la página de detalles Cluster / Health le ayudan a planificar el almacenamiento. Por ejemplo, antes de aprovisionar un nuevo agregado, puede seleccionar un clúster específico de la vista Estado: Todos los clústeres y obtener detalles de capacidad para determinar si el clúster tiene el espacio requerido.



== Pasos

. En el panel de navegación izquierdo, haga clic en *almacenamiento* > *clústeres*.
. En el menú *Ver*, seleccione *Salud: Todos los clusters* para ver información de salud, o *capacidad: Todos los clusters* ver para ver detalles acerca de la capacidad de almacenamiento y utilización en todos los clusters.
. Haga clic en el nombre de un clúster para ver los detalles completos del clúster en la página de detalles *Cluster / Health*.

