---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Active IQ Unified Manager 9.9
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes.html"
  - title: Manos a la obra
    entries:
    - title: Instalación rápida para VMware vSphere
      url: "/qsg-vapp.html"
    - title: Instalación de inicio rápido para Linux
      url: "/qsg-linux.html"
    - title: Instalación de inicio rápido para Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Avisos legales
    url: "/legal-notices.html"
