---
permalink: health-checker/concept-introduction-to-unified-manager-health-monitoring.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager \(anteriormente Unified Manager\ de OnCommand) le ayuda a supervisar un gran número de sistemas que ejecutan el software ONTAP a través de una interfaz de usuario centralizada. La infraestructura de servidor de Unified Manager proporciona escalabilidad y compatibilidad, así como funcionalidades mejoradas de supervisión y notificación.' 
---
= Introducción a la supervisión del estado de Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager (anteriormente Unified Manager de OnCommand) le ayuda a supervisar un gran número de sistemas que ejecutan el software ONTAP a través de una interfaz de usuario centralizada. La infraestructura de servidor de Unified Manager proporciona escalabilidad y compatibilidad, así como funcionalidades mejoradas de supervisión y notificación.

Las funciones clave de Unified Manager incluyen la supervisión, la alerta, la gestión de la disponibilidad y la capacidad de los clusters, la gestión de las capacidades de protección, y la agrupación de datos de diagnóstico y el envío de estos a soporte técnico.

Puede usar Unified Manager para supervisar los clústeres. Cuando se producen problemas en el clúster, Unified Manager notifica los detalles de estos problemas mediante eventos. Algunos eventos también le proporcionan una acción correctiva que puede tomar para resolver los problemas. Es posible configurar alertas para eventos que, cuando se produzcan problemas, se le notificarán por correo electrónico y capturas SNMP.

Puede utilizar Unified Manager para gestionar objetos de almacenamiento en el entorno asociándolos con anotaciones. Puede crear anotaciones personalizadas y asociar de forma dinámica clústeres, máquinas virtuales de almacenamiento (SVM) y volúmenes con las anotaciones mediante las reglas.

También puede planificar los requisitos de almacenamiento de los objetos de clúster mediante la información proporcionada en los gráficos de capacidad y estado del objeto de clúster correspondiente.
