---
permalink: health-checker/reference-configuring-ontap-cluster.html 
sidebar: sidebar 
keywords: NetApp Snapshot backup for Windows,configuring ONTAP cluster 
summary: Antes de configurar Active IQ Unified Manager para backup y restauración de Snapshot para Windows, debe realizar algunas configuraciones previas para equipos host de ONTAP y Windows. 
---
= Configurando clúster de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar Active IQ Unified Manager para backup y restauración de Snapshot para Windows, debe realizar algunas configuraciones previas para equipos host de ONTAP y Windows.

Es posible configurar el clúster de ONTAP mediante el símbolo del sistema o la interfaz de usuario de System Manager. La configuración del clúster de ONTAP implica la configuración de LIF de datos para que estén disponibles como LIF iSCSI para el equipo virtual de almacenamiento. El paso siguiente consiste en configurar un equipo virtual de almacenamiento habilitado para iSCSI mediante la interfaz de usuario de System Manager. Tendrá que configurar una ruta de red estática para esta máquina virtual de almacenamiento a fin de controlar cómo utilizan las LIF la red para el tráfico saliente.

[NOTE]
====
Debe tener un volumen dedicado y un LUN para la configuración de backup. El volumen seleccionado solo debe incluir un LUN. El tamaño de la LUN debe ser al menos el doble del tamaño de datos que se espera que gestione Active IQ Unified Manager.

====
Debe realizar la siguiente configuración:

. Configurar una máquina virtual de almacenamiento habilitada para iSCSI o utilizar una máquina virtual de almacenamiento existente con la misma configuración.
. Configure una ruta de red para el equipo virtual de almacenamiento configurado.
. Configure un volumen de la capacidad adecuada y una única LUN dentro para garantizar que el volumen se dedica únicamente a esta LUN.
. Configure un iGroup en la máquina virtual de almacenamiento.
. Configurar un conjunto de puertos.
. Integre el igroup con el conjunto de puertos.
. Asigne la LUN al igroup.

