---
section: config
title: Realizar tareas administrativas y de configuración
entries:
- title: Configurando Active IQ Unified Manager
  url: "/config/concept-configuring-unified-manager.html"
  entries:
  - title: Descripción general de la secuencia de configuración
    url: "/config/concept-overview-of-the-configuration-sequence.html"
  - title: Acceder a la interfaz de usuario web de Unified Manager
    url: "/config/task-accessing-oncommand-unified-manager-web-ui.html"
  - title: Realizando la configuración inicial de la interfaz de usuario web de Unified
      Manager
    url: "/config/task-performing-the-initial-setup-of-the-unified-manager-web-ui.html"
  - title: Añadir clústeres
    url: "/config/task-adding-clusters.html"
  - title: Configuración de Unified Manager para enviar notificaciones de alerta
    url: "/config/task-configuring-unified-manager-to-send-alert-notifications.html"
    entries:
    - title: Configuración de los ajustes de notificación de eventos
      url: "/config/task-configuring-event-notification-settings.html"
    - title: Habilitación de la autenticación remota
      url: "/config/task-enabling-remote-authentication.html"
    - title: Deshabilitar grupos anidados de la autenticación remota
      url: "/config/task-disabling-nested-groups-from-remote-authentication.html"
    - title: Añadiendo servidores de autenticación
      url: "/config/task-adding-authentication-servers.html"
    - title: Prueba de la configuración de los servidores de autenticación
      url: "/config/task-testing-the-configuration-of-authentication-servers-um-6-0.html"
    - title: Adición de usuarios
      url: "/config/task-adding-users.html"
    - title: Adición de alertas
      url: "/config/task-adding-alerts.html"
  - title: Eventos de EMS que se añaden automáticamente a Unified Manager
    url: "/config/reference-ems-events-that-are-added-automatically-to-unified-manager.html"
  - title: Suscripción a eventos de EMS de ONTAP
    url: "/config/task-subscribing-to-ontap-ems-events.html"
  - title: Gestión de la configuración de autenticación SAML
    url: "/config/concept-managing-saml-authentication-settings-um.html"
    entries:
    - title: Requisitos del proveedor de identidades
      url: "/config/reference-identity-provider-requirements-um.html"
    - title: Habilitación de la autenticación SAML
      url: "/config/task-enabling-saml-authentication-um.html"
  - title: Cambiando la contraseña de usuario local
    url: "/config/task-changing-the-local-user-password.html"
  - title: Configurar el tiempo de espera de inactividad de la sesión
    url: "/config/task-setting-the-session-inactivity-timeout.html"
  - title: Cambie el nombre de host de Unified Manager
    url: "/config/concept-changing-the-unified-manager-host-name.html"
    entries:
    - title: Cambiar el nombre de host de la aplicación virtual de Unified Manager
      url: "/config/task-changing-the-unified-manager-host-name-on-vmware.html"
      entries:
      - title: Generar un certificado de seguridad HTTPS
        url: "/config/task-generating-an-https-security-certificate-ocf.html"
      - title: Reiniciar la máquina virtual de Unified Manager
        url: "/config/task-restarting-the-unified-manager-virtual-machine.html"
    - title: Cambiar el nombre de host de Unified Manager en sistemas Linux
      url: "/config/task-changing-the-unified-manager-host-name-on-rhel-or-centos.html"
  - title: Habilitar y deshabilitar la gestión del almacenamiento basada en políticas
    url: "/config/task-enabling-and-disabling-policy-based-storage-management.html"
- title: Configuración de backup de Unified Manager
  url: "/config/concept-configuring-um-backup.html"
- title: Mediante la consola de mantenimiento
  url: "/config/task-using-the-maintenance-console.html"
  entries:
  - title: Qué funcionalidad proporciona la consola de mantenimiento
    url: "/config/concept-what-functionality-the-maintenance-console-provides.html"
  - title: Lo que hace el usuario de mantenimiento
    url: "/config/concept-what-the-maintenance-user-does.html"
  - title: Capacidades de diagnóstico del usuario
    url: "/config/concept-what-the-diagnostic-user-does.html"
  - title: Acceso a la consola de mantenimiento
    url: "/config/task-accessing-the-maintenance-console.html"
  - title: Acceder a la consola de mantenimiento mediante la consola de la máquina
      virtual de vSphere
    url: "/config/task-accessing-the-maintenance-console-using-vsphere.html"
  - title: Menús de la consola de mantenimiento
    url: "/config/concept-maintenance-console-menu.html"
    entries:
    - title: Menú Configuración de red
      url: "/config/reference-network-configuration-menu.html"
    - title: Menú Configuración del sistema
      url: "/config/reference-system-configuration-menu.html"
    - title: Menú de soporte y diagnóstico
      url: "/config/reference-support-and-diagnostics-menu.html"
    - title: Opciones de menú adicionales
      url: "/config/reference-additional-menu-options.html"
  - title: Cambiar la contraseña del usuario de mantenimiento en Windows
    url: "/config/task-changing-the-maintenance-user-password-on-windows.html"
  - title: Cambiar la contraseña de umadmin en sistemas Linux
    url: "/config/task-changing-the-umadmin-password-on-rhel.html"
  - title: Cambiar los puertos Unified Manager utiliza para los protocolos HTTP y
      HTTPS
    url: "/config/task-changing-the-ports-um-uses-for-http-and-https-protocols.html"
  - title: Se añaden interfaces de red
    url: "/config/task-adding-additional-network-interfaces.html"
  - title: Agregar espacio en disco al directorio de la base de datos de Unified Manager
    url: "/config/concept-adding-disk-space-to-the-unified-manager-database-directory.html"
    entries:
    - title: Adición de espacio al directorio de datos del host Linux
      url: "/config/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html"
    - title: Adición de espacio al disco de datos de la máquina virtual de VMware
      url: "/config/task-adding-space-to-the-data-disk-of-the-vmware-virtual-machine.html"
    - title: Agregar espacio a la unidad lógica del servidor Microsoft Windows
      url: "/config/task-adding-space-to-the-data-disk-of-the-microsoft-windows-server.html"
