---
permalink: install-linux/task-downloading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Debe descargar el archivo Unified Manager.zip del sitio de soporte de NetApp para instalar Unified Manager. 
---
= Descargue Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar Unified Manager``.zip`` Archivo del sitio de soporte de NetApp para instalar Unified Manager.



== Antes de empezar

Debe tener credenciales de inicio de sesión en el sitio de soporte de NetApp.



== Acerca de esta tarea

Puede descargar el mismo paquete de instalación de Unified Manager para sistemas Red Hat Enterprise Linux y CentOS.



== Pasos

. Inicie sesión en el sitio de soporte de NetApp y desplácese hasta la página *Descargar* para Unified Manager: https://["Sitio de soporte de NetApp"]
. Seleccione la versión requerida de Unified Manager y acepte el contrato de licencia para usuarios finales (CLUF).
. Descargue el archivo del instalador de Unified Manager para Linux y guarde el `.zip` archivo en un directorio del sistema de destino.
+
[NOTE]
====
Asegúrese de descargar la versión correcta del archivo de instalación del sistema Red Hat Enterprise Linux. Según si tiene Red Hat Enterprise Linux 7 o 8 instalado, asegúrese de descargar la versión adecuada de Unified Manager``.zip`` archivo.

====
. Compruebe la suma de comprobación para asegurarse de que el software se ha descargado correctamente.

