---
permalink: install-linux/task-upgrading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Puede actualizar desde Unified Manager 9.7 o 9.8 a 9.9 descargando y ejecutando el archivo de instalación en la plataforma Red Hat. 
---
= Actualizar Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar desde Unified Manager 9.7 o 9.8 a 9.9 descargando y ejecutando el archivo de instalación en la plataforma Red Hat.



== Antes de empezar

* El sistema donde se actualiza Unified Manager debe cumplir con los requisitos del sistema y del software.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos del sistema de hardware]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Requisitos de instalación y software de Red Hat y CentOS]

* Debe instalar o actualizar a la versión correcta de OpenJDK antes de actualizar Unified Manager.
+
xref:task-upgrading-openjdk-on-linux-ocum.adoc[Actualizar JRE en Linux]

* MySQL Community Edition se actualiza automáticamente durante la actualización de Unified Manager. Si la versión instalada de MySQL en el sistema es anterior a 8.0.25, el proceso de actualización de Unified Manager actualiza automáticamente MySQL a 8.0.25.
+
Sin embargo, es posible que desee actualizar MySQL a la última versión secundaria del sistema. Antes de actualizar a la siguiente versión secundaria, asegúrese de que la versión base de MySQL en el sistema sea 8.0.25.

* Debe disponer de una suscripción al administrador de suscripciones de Red Hat Enterprise Linux.
* Para evitar la pérdida de datos, debe haber creado un backup de la base de datos de Unified Manager en caso de que haya un problema durante la actualización. También se recomienda mover el archivo de copia de seguridad de `/opt/netapp/data` directorio a una ubicación externa.
* Durante la actualización, es posible que se le solicite que confirme si desea mantener la configuración predeterminada anterior para conservar los datos de rendimiento durante 13 meses o si desea cambiarla a 6 meses. Al confirmar, se depuran los datos de rendimiento históricos después de 6 meses.
* Debe haber completado todas las operaciones en ejecución, ya que Unified Manager no está disponible durante el proceso de actualización.




== Pasos

. Inicie sesión en el servidor Red Hat Enterprise Linux o CentOS de destino.
. Descargue el paquete de Unified Manager en el servidor.
+
xref:task-downloading-unified-manager.adoc[Descarga de Unified Manager para Red Hat o CentOS]

. Desplácese hasta el directorio de destino y expanda el paquete Unified Manager: `unzip ActiveIQUnifiedManager-<version\>.zip`
+
Los módulos RPM necesarios para Unified Manager se descomprimen en el directorio de destino.

. Compruebe que el siguiente módulo esté disponible en el directorio: `ls *.rpm`
+
** `netapp-um<version\>.x86_64.rpm`


. Para los sistemas que no están conectados a Internet o que no utilizan los repositorios de Red Hat Enterprise Linux, realice los siguientes pasos para determinar si falta algún paquete necesario y descargue esos paquetes:
+
.. Consulte la lista de paquetes disponibles y no disponibles: `yum install netapp-um<version\>.x86_64.rpm --assumeno`
+
Los elementos de la sección «'instalación:'» son los paquetes que están disponibles en el directorio actual, y los elementos de la sección «'instalación de dependencias:'» son los paquetes que faltan en su sistema.

.. En un sistema diferente con acceso a Internet, ejecute el siguiente comando para descargar los paquetes que faltan. `yum install package_name --downloadonly --downloaddir=.`
+
Los paquetes se descargan en el directorio especificado como `–downloaddir=.`

+
Puesto que el complemento "'yum-plugin-downloadonly'" no siempre está activado en los sistemas Red Hat Enterprise Linux, es posible que tenga que habilitar la funcionalidad para descargar un paquete sin instalarlo:``yum install yum-plugin-downloadonly``

.. Cree un nuevo directorio en el sistema de instalación y copie los paquetes descargados desde el sistema conectado a Internet.
.. Cambie los directorios al nuevo directorio del sistema de instalación y ejecute el siguiente comando para instalar MySQL Community Edition, junto con sus dependencias. `yum install *.rpm`


. Ejecute la secuencia de comandos previa a la instalación para asegurarse de que no haya ninguna configuración del sistema ni ningún software instalado que pueda entrar en conflicto con la actualización: `sudo ./pre_install_check.sh`
+
La secuencia de comandos de preinstalación comprueba que el sistema tiene una suscripción válida a Red Hat y que tiene acceso a los repositorios de software necesarios. Si el script identifica algún problema, debe corregir los problemas antes de actualizar Unified Manager.

. Actualice Unified Manager con el siguiente script: `upgrade.sh`
+
Esta secuencia de comandos ejecuta automáticamente los módulos RPM, actualizando el software compatible necesario y los módulos Unified Manager que se ejecutan en ellos. Además, el script de actualización comprueba si hay alguna configuración del sistema o cualquier software instalado que pueda entrar en conflicto con la actualización. Si el script identifica algún problema, debe corregir los problemas antes de actualizar Unified Manager.

. Una vez completada la actualización, desplácese hacia atrás por los mensajes hasta que vea el mensaje que muestra una dirección IP o una URL para la interfaz de usuario web de Unified Manager, el nombre de usuario de mantenimiento (umadmin) y la contraseña predeterminada.
+
El mensaje es similar al siguiente:

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----




== Después de terminar

Introduzca la dirección IP o URL especificada en un explorador web compatible para iniciar la interfaz de usuario web de Unified Manager y, a continuación, inicie sesión con el mismo nombre de usuario de mantenimiento (umadmin) y la misma contraseña que configuró anteriormente.
